name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write  # needed for uploading SARIF reports

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: stan454
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t stan454/ypostservice:${{ github.sha }} ./YPostService

    - name: Scan Docker image with Trivy and output SARIF
      uses: aquasecurity/trivy-action@v0.27.1
      with:
        image-ref: stan454/ypostservice:${{ github.sha }}
        format: sarif
        output: trivy-results.sarif
        severity: CRITICAL,HIGH

    - name: Upload Trivy SARIF report to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-results.sarif

    - name: Push Docker image to Docker Hub
      run: docker push stan454/ypostservice:${{ github.sha }}

    - name: Tag Docker image as latest and push
      run: |
        docker tag stan454/ypostservice:${{ github.sha }} stan454/ypostservice:latest
        docker push stan454/ypostservice:latest
