name: Run Tests and CodeQL Analysis

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  test:
    name: Run xUnit Tests and CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release

  
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: test  

    steps:
      # Checkout repository for CodeQL analysis
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'csharp'  

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
