name: Run Tests and CodeQL Analysis

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  test:
    name: Run xUnit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release

  postman-tests:
    name: Run Postman Integration Tests
    runs-on: ubuntu-latest
    needs: test  # Run after xUnit tests succeed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection with Newman
        run: newman run ./PostServiceTests/YPostApiTests.postman_collection.json
        # Optional: add --environment ./postman/environment.json if you use environment variables

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: [test, postman-tests]  # Runs only after both test jobs succeed

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [csharp]
        build-mode: [manual]  # Manual build mode may be necessary if autobuild isn't working for your .NET project
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          build-mode: manual
    
      - name: Build solution manually
        run: dotnet build --configuration Release
    
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
